# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Users/TEMP.PCLABS.000/Downloads/NEW/NEW.cache/wt [current_project]
set_property parent.project_path D:/Users/TEMP.PCLABS.000/Downloads/NEW/NEW.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib -sv {
  D:/Users/TEMP.PCLABS.000/Downloads/NEW/NEW.srcs/sources_1/new/keypad4X4.sv
  D:/Users/TEMP.PCLABS.000/Downloads/NEW/NEW.srcs/sources_1/new/display_8x8.sv
  D:/Users/TEMP.PCLABS.000/Downloads/NEW/NEW.srcs/sources_1/new/topmodule.sv
}
read_xdc D:/Users/TEMP.PCLABS.000/Downloads/NEW/NEW.srcs/constrs_1/new/const.xdc
set_property used_in_implementation false [get_files D:/Users/TEMP.PCLABS.000/Downloads/NEW/NEW.srcs/constrs_1/new/const.xdc]

synth_design -top topmodule -part xc7a35tcpg236-1
write_checkpoint -noxdef topmodule.dcp
catch { report_utilization -file topmodule_utilization_synth.rpt -pb topmodule_utilization_synth.pb }
